### ISSUE TITLE
scrape a page or a group

### ISSUE THREAD

**Issue by treble2019** [akaessens/NoFbEventScraper#20]
The app is great. I am wondering if the same can be done to scrap and follow a public group. 

example: https://www.facebook.com/groups/InstantPotCommunity/

Would it be possible to repeat something like:
https://github.com/austinhuang0131/instagrabber
in your scraper.
(obviously only public - and no login - type group or persons).

thanks for your great work!

**Comment by akaessens** [comment]
Hi @treble2019 , thank you!

The purpose of this application is not to replace the whole  "facebook experience" with an open source alternative client, this would probably be very difficult to maintain. A[ quick look into instagrabber](https://github.com/austinhuang0131/instagrabber/issues/100) does show the difficulties with keeping up with instagram's API and i have huge respect to his/their commitment. 

For browsing through it, there are many [wrapper apps](https://github.com/AllanWang/Frost-for-Facebook) available. 

I've written this app, because the only thing that kept me on that network was their events and i often receive some links to them.

If you are referring to events inside groups or pages (like [this](https://www.facebook.com/pg/blindguardian/events/)) , i think it might be interesting to look more into it. This would of course mean huge changes and will take me quite some time.

I found [Hypezig](https://gitlab.com/intergalacticsuperhero/hypezig), which does scrape facebook pages, but it is using the facebook API to collect events.

**Comment by treble2019** [comment]
Thank you for the suggestions!
